# permissions for end users to edit probeassistants.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: probeassistant-editor-role
rules:
- apiGroups:
  - apps.k8s.operatoros.io
  resources:
  - probeassistants
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.k8s.operatoros.io
  resources:
  - probeassistants/status
  verbs:
  - get
