# permissions for end users to view probeassistants.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: probeassistant-viewer-role
rules:
- apiGroups:
  - apps.k8s.operatoros.io
  resources:
  - probeassistants
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.k8s.operatoros.io
  resources:
  - probeassistants/status
  verbs:
  - get
