
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps.k8s.operatoros.io
  resources:
  - probeassistants
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.k8s.operatoros.io
  resources:
  - probeassistants/finalizers
  verbs:
  - update
- apiGroups:
  - apps.k8s.operatoros.io
  resources:
  - probeassistants/status
  verbs:
  - get
  - patch
  - update
